language: python

python:
    - "2.7"

services:
    - redis-server

install:
    - pip install tornado
    - pip install tornado_json
    - pip install tinydb
    - pip install coveralls

script: coverage run tests/execute.py

after_success:
    coveralls

