language: python

python:
  - "2.7"

install:
  - pip install tornado
  - pip install python-coveralls
  - pip install coverage
  - pip install httpretty
  - pip install nose

script: 
  - python setup.py install
  - nosetests

after_success:
  - coveralls

